### ISSUE TITLE
embnet_flatten_layer.h and embnet_tensor.h missing

### ISSUE THREAD

**Issue by tswl** [GValiente/pocket-tensor#1]
In pt_flatten_layer.cpp there are two includes that are not included in the repo: embnet_flatten_layer.h and embnet_tensor.h. Also tries to subclass unknown class FixedLayer...

Otherwise this looks really interesting and I would love to try it out. :-)

**Comment by GValiente** [comment]
pt_flatten_layer.cpp is not necessary anymore, so it has been removed.

Thanks!
