### ISSUE TITLE
Input Layer ..?

### ISSUE THREAD

**Issue by furkank75** [GValiente/pocket-tensor#12]
Hi, 
I would like use your source code. 
My Model have a Input Layer.. But I became an error.. 
`AssertionError: Unsupported layer type: InputLayer`

Is there a possibility to use your code with an Input Layer??

**Comment by GValiente** [comment]
I just have added Input layers support.

**Comment by furkank75** [comment]
Ok now i have the Same Error with: Conv2DTranapose Layer..

**Comment by GValiente** [comment]
Conv2DTranspose layers are not currently supported.

Since Input layers are now supported, I'll close this issue.
