### ISSUE TITLE
iOS/Xcode support

### ISSUE THREAD

**Issue by Yak0xff** [GValiente/pocket-tensor#2]
Great Job! 

I want to use this lib in iOS app for some AI Task, but I don't know  How to use. In my Xcode project, the libsimdpp didn‘t import. Please help me.  Thanks

**Comment by GValiente** [comment]
Hi!

I don't have any iOS device to do a quick test nor experience with Xcode, but you should be able to [generate a Xcode project from a CMakeLists.txt file](https://stackoverflow.com/questions/41829852/how-to-create-xcode-project-from-already-existing-git-cmake-project) without too much problems.

You can also [add the pocket-tensor cpp files to you existing project](https://stackoverflow.com/questions/5495822/how-to-add-the-cpp-file-in-xcode-project). If you try this, [remember to add libsimdpp headers too](https://stackoverflow.com/questions/2093069/xcode-how-to-include-c-library-and-header-file-to-cocoa-project).

Wathever you try please tell me how it's going.

**Comment by Yak0xff** [comment]
That's very useful, i had build the Xcode project using the **CMake -g Xcode**, but when compile the project, has flow image's errors:



![img](https://user-images.githubusercontent.com/5406305/46912847-22846e00-cfb3-11e8-9238-5aec0b841f08.png)

**Comment by GValiente** [comment]
It seems that those builtin_ia32_* identifiers are x86 instructions, instead of ARM ones.

Make sure that in the pt_tweakme.h header file:
- `SIMDPP_ARCH_ARM_NEON_FLT_SP` macro is defined.
- `SIMDPP_ARCH_X86_*` macros are not defined.

**Comment by Yak0xff** [comment]
That's work! The Xcode project has build succeeded, very thank you.
i will  run the 1D-CNN model in this lib, hope that's OK. Thanks again.

**Comment by Yak0xff** [comment]
```
#ifdef __arm__
    #define SIMDPP_ARCH_ARM_NEON_FLT_SP
#else
    #if PT_FMADD_ENABLE
        #define SIMDPP_ARCH_X86_AVX2
        #define SIMDPP_ARCH_X86_FMA3
    #else
        #define SIMDPP_ARCH_X86_AVX
    #endif
#endif
```

this is  pt_tweakme.h header file's define,  `#ifdef __arm__` didn't work?

**Comment by GValiente** [comment]
> this is pt_tweakme.h header file's define, `#ifdef __arm__` didn't work?
It seems so.

I'll close this issue, if you have any other problem feel free to open a new one.
