### ISSUE TITLE
error on process 2d image

### ISSUE THREAD

**Issue by kalluwa** [GValiente/pocket-tensor#4]
Hi
Thanks for your great work.
i have encountered a problem when processing mnist image classification,here is my code:
```
import numpy as np
from keras.models import Sequential
from keras.layers import Dense,Conv2D,Flatten,Dropout,MaxPooling2D
from keras.optimizers import SGD, Adam, RMSprop
from keras.datasets import mnist
from kerasify import export_model
from keras.utils import np_utils

(X_train, y_train), (X_test, y_test) = mnist.load_data()

X_train = X_train.reshape(X_train.shape[0],28,28,1).astype('float32')
X_test = X_test.reshape(X_test.shape[0],28,28,1).astype('float32')
X_train /= 255.0
X_test /= 255.0

#test_x = np.random.rand(10, 10).astype('f')
#test_y = np.random.rand(10).astype('f')
batch_size = 128
nb_classes = 10
nb_epoch = 1

Y_train = np_utils.to_categorical(y_train, nb_classes)
Y_test = np_utils.to_categorical(y_test, nb_classes)

#from your readme
model = Sequential()
model.add(Conv2D(32, kernel_size=(3, 3), activation='relu', input_shape=(28, 28, 1)))
model.add(Conv2D(64, (3, 3), activation='relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Dropout(0.25))
model.add(Flatten())
model.add(Dense(128, activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(10, activation='sigmoid'))

model.compile(loss='categorical_crossentropy',
              optimizer=RMSprop(),
              metrics=['accuracy'])

model.fit(X_train, Y_train,
                    batch_size=batch_size, nb_epoch=nb_epoch,
                    verbose=1, validation_data=(X_test, Y_test))

export_model(model, 'example.model')
```

and i import the model into a cpp project

```
#include <iostream>
#include "pt_model.h"
#include "pt_tensor.h"

int main()
{
	// Initialize model:
	auto model = pt::Model::create("example.model");
	// REQUIRE(model);

	// Create input tensor:
	pt::Tensor in(28,28,1);
	float* raw = new float[28 * 28 * 1];
	for (size_t i = 0; i < 28; i++)
	{
		for (size_t j = 0; j < 28; j++)
		{
			raw[i * 28 + j] = 0;
			if (j > 12 && j < 16)
				raw[i * 28 + j] = 1;
		}
	}

	pt::Tensor::DataVector rawInput(28*28);
	for (size_t i = 0; i < 28*28; i++)
	{
		rawInput[i]=(raw[i]);
	}
	in.setData(rawInput);

	// Run prediction:
	pt::Tensor out;

//GOT EXCEPTION HERE
	bool success = model->predict(std::move(in), out);
	// REQUIRE(success);

	// Print output:
	std::cout << out << std::endl;

	system("pause");
	return 0;
}

```
and i got a exception:

new_scalar.cpp
![image](https://user-images.githubusercontent.com/9412335/50760727-80b7a900-12a3-11e9-8f55-a21de34a3bab.png)
it's weird why malloc new memory failed.
is my data initialization code wrong?

**Comment by GValiente** [comment]
Hi,

I'm not able to reproduce the exception on my machine (Ubuntu 18 with GCC 7.3.0).

However, you don't need to jump through so much hoops to initialize the input tensor (there's a memory leak with the raw array, BTW :) ).

Please try this code:

```cpp
#include <iostream>
#include "pt_model.h"
#include "pt_tensor.h"

int main()
{
        // Initialize model:
        auto model = pt::Model::create("example.model");
        // REQUIRE(model);

        // Create input tensor:
        pt::Tensor in(28, 28, 1);

        for(std::size_t i = 0; i < 28; i++)
        {
            for(std::size_t j = 0; j < 28; j++)
            {
                in(i, j, 0) = 0;

                if(j > 12 && j < 16)
                {
                    in(i, j, 0) = 1;
                }
            }
        }

        // Run prediction:
        pt::Tensor out;
        bool success = model->predict(std::move(in), out);
        // REQUIRE(success);

        // Print output:
        std::cout << out << std::endl;

        system("pause");
        return 0;
}
```

**Comment by kalluwa** [comment]
thanks for your reply.
it outputs the right value after i changed the tensor input method in your way.
many many thanks.

**Comment by kalluwa** [comment]
another question here:

when i run same exe multiple times, it can core dump or output successfully,  as the following pic  showing:

![snipaste_20190108_162549](https://user-images.githubusercontent.com/9412335/50818741-ee76da00-1362-11e9-9af9-d4358ab1284f.png)

```c++
int main(int argc,char** argv)
{
	if (argc <= 1)
		return 0;

	std::cout << "loading model" << std::endl;
	// Initialize model:
	auto model = pt::Model::create("example.model");
	// REQUIRE(model);

	//loading info text
	std::string info_path = argv[1];
	std::vector<std::pair<std::string, int>> rs = extract_lines_from_file(info_path);


	std::cout << "testing" << std::endl;
	auto start = clock();
	int count = 0;
	
	int test_size = rs.size();
	if(argc>2)
		if(test_size > atoi(argv[2]))
			test_size = atoi(argv[2]);

	for (size_t i = 0; i < test_size; i++)
	{

		int width, height, channels;
		unsigned char* img = stbi_load(rs[i].first.c_str(), &width, &height, &channels, 0);

		// Create input tensor:
		pt::Tensor in(28, 28, 1);
		for (size_t i = 0; i < 28; i++)
		{
			for (size_t j = 0; j < 28; j++)
			{
				float v = img[channels*(i * 28 + j)] / 255.0f;
				in(i, j, 0) = v;
			}
		}

		// Run prediction:

		pt::Tensor out;
		bool success = model->predict(std::move(in), out);
		// REQUIRE(success);
		int maxidx = -1;
		float ratio = -1.0;
		for (size_t i = 0; i < out.getSize(); i++)
		{
			if (ratio < out(i)) {
				ratio = out(i); maxidx = i;
			}
		}
		if (rs[i].second == maxidx)
		{
			count++;
		}
		STBI_FREE(img);
	}
	auto duration = clock() - start;
	// Print output:
	std::cout << duration * 1000 / (float)CLOCKS_PER_SEC << "ms" << std::endl;
	std::cout << "==========================================" << std::endl;
	std::cout << "acc:" << count <<"/"<< test_size << std::endl;

	//system("pause");
	return 0;
}
```
when exec it on debug mode, a exception is alwary throwed on:
aligned_allocator.h
```c++
void deallocate(T* p, std::size_t n) const
    {
        (void) n;
        if (!p) {
            return;
        }
        char** pptr = reinterpret_cast<char**>(p);
        delete[](*(pptr - 1));
    }
```
could it be a problem of  vs2015?

**Comment by GValiente** [comment]
A lot of things unrelated to pocket-tensor could go wrong in that code.

If you can debug the application, you should be able to get the call stack just when the exception is thrown (https://blogs.msdn.microsoft.com/devops/2015/01/07/understanding-exceptions-while-debugging-with-visual-studio/). With the call stack you can guess the source of the exception.

FYI, pocket-tensor has been tested with vs2017, not vs2015.
Have you tried to build and run the unit tests on your machine?

**Comment by kalluwa** [comment]
all test passed on vs2015.
and i think it should be memory destroy/free code error on libsimdpp : 
everything works fine after i comment **delete[](*(pptr - 1));** (ignore the memory leaks).

**Comment by kalluwa** [comment]
and memory usage doesn't change in release mode( maybe no need to use **delete[](*(pptr - 1));**)
> 5000 mnist images are tested, memory usage is stable (6.4~6.5MB)

**Comment by kalluwa** [comment]
so i changed this line:
```
using DataVector = std::vector< Type >;//, simdpp::aligned_allocator<Type, Alignment >> ;
```
5000 mnist images are tested, memory usage is stable (6.4~6.5MB)

**Comment by GValiente** [comment]
It's weird... with the DataVector change, you are allowing unaligned access to vector code, so it shouldn't work.
Which tensor is throwing the exception?
On which iteration?

BTW, you are not checking if the prediction has failed or not (`bool success`). 
Please check it before accesing the output tensor.

**Comment by kalluwa** [comment]
I know it's incorrect and weird.   
sorry for late reply,  I use vs2017 to rebuild the project.
and no exception is throwed under Debug mode.

while I switch in Release mode,  the program crash again. emmmmm
(no callstack is avaible this time ,so I don't know which tensor trigger the exception,
and no crash after remove **delete[](*(pptr - 1));**

here is my testing code:
[123.zip](https://github.com/GValiente/pocket-tensor/files/2745009/123.zip)

**Comment by GValiente** [comment]
If you remove all stbi code, remove the `extract_lines_from_file` call and fill the input tensor with random values, do you keep receiving exceptions?

**Comment by GValiente** [comment]
On my machine, if I remove all stbi code and fill the input tensor with random values, I don't receive any exception on debug nor release.

**Comment by kalluwa** [comment]
yes, I test it without stb. It seems that STBI_FREE(img) cause the problem.
maybe memory structure is broken after this operation.
