### ISSUE TITLE
build benchmark application fatal error: Eigen/Core: No such file or directory

### ISSUE THREAD

**Issue by globalmaster** [GValiente/pocket-tensor#7]
Hi,
I followed readme.md ,run python3 make_tests.py and build tests successfully.
I install eigen3 via apt on Ubuntu16.04.
When I build benchmark application, I got this error. How can I fix this error? Can you help me?

[ 97%] Building CXX object benchmark/CMakeFiles/pocket-tensor-benchmark.dir/src/pt_bench.cpp.o
In file included from /media/jack/code/clion_kdevelop/OCR/pocket-tensor/benchmark/3rd_party/frugally-deep/lib/include/fdeep/fdeep.hpp:9:0,
                 from /media/jack/code/clion_kdevelop/OCR/pocket-tensor/benchmark/src/fd_bench.cpp:6:
/media/jack/code/clion_kdevelop/OCR/pocket-tensor/benchmark/3rd_party/frugally-deep/lib/include/fdeep/common.hpp:23:22: fatal error: Eigen/Core: No such file or directory
compilation terminated.
benchmark/CMakeFiles/pocket-tensor-benchmark.dir/build.make:88: recipe for target 'benchmark/CMakeFiles/pocket-tensor-benchmark.dir/src/fd_bench.cpp.o' failed
make[2]: *** [benchmark/CMakeFiles/pocket-tensor-benchmark.dir/src/fd_bench.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
CMakeFiles/Makefile2:151: recipe for target 'benchmark/CMakeFiles/pocket-tensor-benchmark.dir/all' failed
make[1]: *** [benchmark/CMakeFiles/pocket-tensor-benchmark.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by GValiente** [comment]
Hi,

Eigen is required by frugally-deep.

Take a look at [frugally-deep's installation guide](https://github.com/Dobiasd/frugally-deep/blob/master/INSTALL.md).

**Comment by globalmaster** [comment]
> Hi,
> 
> Eigen is required by frugally-deep.
> 
> Take a look at [frugally-deep's installation guide](https://github.com/Dobiasd/frugally-deep/blob/master/INSTALL.md).

Thank you for your replay.
I solved this problem and get another problem:

[ 97%] Building CXX object benchmark/CMakeFiles/pocket-tensor-benchmark.dir/src/pt_bench.cpp.o
In file included from /media/jack/code/clion_kdevelop/OCR/pocket-tensor/benchmark/3rd_party/frugally-deep/lib/include/fdeep/fdeep.hpp:9:0,
                 from /media/jack/code/clion_kdevelop/OCR/pocket-tensor/benchmark/src/fd_bench.cpp:6:
/media/jack/code/clion_kdevelop/OCR/pocket-tensor/benchmark/3rd_party/frugally-deep/lib/include/fdeep/common.hpp:31:27: fatal error: fplus/fplus.hpp: No such file or directory
compilation terminated.
benchmark/CMakeFiles/pocket-tensor-benchmark.dir/build.make:88: recipe for target 'benchmark/CMakeFiles/pocket-tensor-benchmark.dir/src/fd_bench.cpp.o' failed
make[2]: *** [benchmark/CMakeFiles/pocket-tensor-benchmark.dir/src/fd_bench.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
CMakeFiles/Makefile2:151: recipe for target 'benchmark/CMakeFiles/pocket-tensor-benchmark.dir/all' failed
make[1]: *** [benchmark/CMakeFiles/pocket-tensor-benchmark.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by GValiente** [comment]
FunctionalPlus is required by frugally-deep too.

To install all its dependencies on an Ubuntu OS, please follow [frugally-deep's installation guide](https://github.com/Dobiasd/frugally-deep/blob/master/INSTALL.md) instructions (that's what worked for me).

**Comment by GValiente** [comment]
Since this issue is related to frugally-deep, I'll close it.

However, if you have problems with pocket-tensor building, please feel free to create another issue.
