### ISSUE TITLE
Includes UTF-8 with BOM

### ISSUE THREAD

**Issue by micharaze** [GValiente/pocket-tensor#8]
Hello, I used your library with Netbeans. There are problems with Netbeans when source or include files are in UTF-8 format with BOM. It shows Netbeans errors even though the building itself works. 

The problem is described here:
https://stackoverflow.com/questions/14913243/netbeans-7-2-shows-unable-to-resolve-identifier-although-build-is-successful

Some of your include files are in UTF-8 format with BOM. If i converted the files to UTF-8 without BOM, the Netbeas errors are wanished. 

I converted the files with:
`dos2unix *.h`

So maybe it's good if you convert the files in the project all in UTF-8 without BOM to fix bugs like mine.

**Comment by GValiente** [comment]
I have executed `dos2unix` on all source files.

Please tell me if your issue has been fixed or not.

**Comment by micharaze** [comment]
fixed!
