### ISSUE TITLE
feature request support for onnx format

### ISSUE THREAD

**Issue by bitnick10** [GValiente/pocket-tensor#9]

**Comment by GValiente** [comment]
Hi,

Currently, pocket-tensor is designed for executing high level keras models, not low level ones, so I'm not sure if it is possible to support onnx models without making major changes in the library.

Do you know about any onnx 2 keras converter?

**Comment by bitnick10** [comment]
Can't find some lib transform onnx 2 keras, why not just using https://github.com/onnx/onnxmltools save keras model to onnx, and pocket-tensor lib can read onnx.

**Comment by GValiente** [comment]
> why not just using https://github.com/onnx/onnxmltools save keras model to onnx, and pocket-tensor lib can read onnx.

Because pocket-tensor implements high level keras layers, not low level onnx operators.

**Comment by bitnick10** [comment]
it's ok for your design philosophy.I'll find other ways.
